type Account @entity {
  "Address"
  id: ID!

  "Vault positions":
  accountVaults: [AccountVault!]! @derivedFrom(field: "account")

  "Total assets deposited"
  deposits: [Deposit!]! @derivedFrom(field: "account")

  "Total assets withdrawn"
  Withdraws: [Withdraw!]! @derivedFrom(field: "account")

  "Total shares transferred to"
  sharesReceived: [Transfer!]! @derivedFrom(field: "to")

  "Total shares transferred from"
  sharesSent: [Transfer!]! @derivedFrom(field: "from")
}
