type AccountVault @entity {
  "Generated ID - account-vault"
  id: ID!

  "Vault"
  vault: Vault!

  "Account"
  account: Account!

  "Share balance (unlocked)"
  sharesBalance: BigDecimal!

  "Shares locked"
  sharesLocked: BigDecimal!

  "Total assets deposited"
  totalAssetsDeposited: BigDecimal!

  "Total assets withdrawn"
  totalAssetsWithdrawn: BigDecimal!

  "Locked Deposits"
  lockedDeposits: [LockedDeposit!]! @derivedFrom(field: "accountVault")

  "Locked deposit transactions"
  lockedDepositTransactions: [LockedDepositTransaction!]! @derivedFrom(field: "accountVault")

  "Deposits"
  deposits: [Deposit!]! @derivedFrom(field: "accountVault")

  "Withdraws"
  withdraws: [Withdraw!]! @derivedFrom(field: "accountVault")

  "Total shares transferred to"
  sharesReceived: [Transfer!]! @derivedFrom(field: "toAccountVault")

  "Total shares transferred from"
  sharesSent: [Transfer!]! @derivedFrom(field: "fromAccountVault")

  "Total locked deposits transferred to"
  lockedDepositsReceived: [LockedDepositTransfer!]! @derivedFrom(field: "toAccountVault")

  "Total locked deposits transferred from"
  lockedDepositsSent: [LockedDepositTransfer!]! @derivedFrom(field: "fromAccountVault")
}
