type Account @entity {
  "Address"
  id: ID!

  "Vault positions"
  accountVaults: [AccountVault!]! @derivedFrom(field: "account")

  "Total assets deposited"
  deposits: [Deposit!]! @derivedFrom(field: "account")

  "Total assets withdrawn"
  Withdraws: [Withdraw!]! @derivedFrom(field: "account")

  "Total locked deposits"
  lockedDeposits: [LockedDeposit!]! @derivedFrom(field: "account")

  # Fields below are transaction based and are not accurate current balances

  "Total locked deposit transactions"
  lockedDepositTransactions: [LockedDepositTransaction!]! @derivedFrom(field: "account")

  "Total deposits unlocked"
  depositsUnlocked: [DepositUnlocked!]! @derivedFrom(field: "account")

  "Total shares transferred to"
  sharesReceived: [Transfer!]! @derivedFrom(field: "to")

  "Total shares transferred from"
  sharesSent: [Transfer!]! @derivedFrom(field: "from")

  "Total locked deposits transferred to"
  lockedDepositsReceived: [LockedDepositTransfer!]! @derivedFrom(field: "to")

  "Total locked deposits transferred from"
  lockedDepositsSent: [LockedDepositTransfer!]! @derivedFrom(field: "from")
}
