type AccountVault @entity {
  "Generated ID - account-vault"
  id: ID!

  "Vault"
  vault: Vault!

  "Account"
  account: Account!

  "Share balance"
  sharesBalance: BigDecimal!

  "Total assets supplied"
  totalAssetsSupplied: BigDecimal!

  "Total assets redeemed"
  totalAssetsRedeemed: BigDecimal!

  "Deposits"
  deposits: [Deposit!]! @derivedFrom(field: "accountVault")

  "Withdraws"
  withdraws: [Withdraw!]! @derivedFrom(field: "accountVault")

  "Total shares transferred to"
  sharesReceived: [Transfer!]! @derivedFrom(field: "toAccountVault")

  "Total shares transferred from"
  sharesSent: [Transfer!]! @derivedFrom(field: "fromAccountVault")
}
