type Deposit @entity {
  "Generated ID - transaction-log"
  id: ID!

  "Vault"
  vault: Vault!

  "Account making deposit"
  account: Account!

  "Account vault"
  accountVault: AccountVault!

  "Number of assets deposited"
  assets: BigInt!

  "Number of new shares minted"
  shares: BigInt!

  "Transaction"
  transaction: Transaction!
}
