type LockedDepositTransaction @entity {
  "Generated ID - deposit ID-transaction ID"
  id: ID!

  "Vault"
  vault: Vault!

  "Account making transaction"
  account: Account!

  "Account vault"
  accountVault: AccountVault!

  "Locked deposit"
  lockedDeposit: LockedDeposit!

  "Transaction"
  transaction: Transaction!
}

type LockedDeposit @entity {
  "Locked deposit ID"
  id: ID!

  "Vault"
  vault: Vault!

  "Account owning locked deposit"
  account: Account!

  "Account vault"
  accountVault: AccountVault!

  "Number of assets deposited"
  assetsDeposited: BigDecimal!

  "Number of assets discounted"
  assetsDiscount: BigDecimal!

  "Discount percentage"
  discountP: BigDecimal!

  "Number of new shares minted"
  shares: BigDecimal!

  "Lock duration"
  lockDuration: Int!

  "Still active"
  active: Boolean!
}
