type Transfer @entity {
  "Generated ID - transaction-log"
  id: ID!

  "Vault"
  vault: Vault!

  "Sender"
  from: Account!

  "From account vault"
  fromAccountVault: AccountVault!

  "Receiver"
  to: Account!

  "To account vault"
  toAccountVault: AccountVault!

  "Number of new shares minted"
  shares: BigDecimal!

  "Market rate at time of transfer"
  assetValue: BigDecimal!

  "Transaction"
  transaction: Transaction!
}
