type Transfer @entity {
  "Generated ID - transaction-log"
  id: ID!

  "Vault"
  vault: Vault!

  "Sender"
  from: Account!

  "Receiver"
  to: Account!

  "Number of new shares minted"
  shares: BigInt!

  "Market rate at time of transfer"
  approxAssetValue: BigInt!

  "Transaction"
  transaction: Transaction!
}
