type Vault @entity {
  "Vault address"
  id: ID!

  "Epoch ID"
  epoch: BigInt!

  "Exchange rate"
  shareToAssets: BigDecimal!

  "Exchange rate (raw)"
  shareToAssetsRaw: BigInt!

  "Asset decimals"
  assetDecimals: Int!

  "Block number of last update"
  lastUpdateBlock: BigInt!

  "Timestamp of last update"
  lastUpdateTimestamp: BigInt!

  "Deposits to vault"
  deposits: [Deposit!]! @derivedFrom(field: "vault")

  "Withdraws from vault"
  withdraws: [Withdraw!]! @derivedFrom(field: "vault")

  "Transfers of vault shares"
  transfers: [Transfer!]! @derivedFrom(field: "vault")
}
