type Withdraw @entity {
  "Generated ID - transaction-log"
  id: ID!

  "Account making deposit"
  account: Account!

  "Number of new shares deposited"
  shares: BigInt!

  "Number of assets received"
  assets: BigInt!

  "Transaction hash"
  txHash: Bytes!

  "Timestamp of deposit"
  timestamp: BigInt!

  "Block number of deposit"
  blockNumber: BigInt!
}
